name: unit-tests
on:
  pull_request: {}
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Run Tests and Generate JUnit XML
        run: pytest --junitxml=test-results/results.xml tests/test_my_functions.py
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}